library(tidyverse)
library(dbplyr)
library(tidygraph)
library(jsonlite)
library(igraph)
library(lubridate)
library(intergraph)
library(networkD3)
library(callr)
library(shiny)
library(shinyWidgets)
library(shinydashboard)
library(shinycssloaders)
library(shinyjs)
library(htmlwidgets)
library(htmltools)
library(bsplus)
library(rclipboard)
library(httr)
library(plotly)
library(ggVennDiagram)
library(qrencoder)
library(stringi)
library(DBI)
library(RPostgreSQL)
library(pool)
library(gamlss)
library(googleCloudRunner)

# load data and functions for applications
source('inst/global.R')

# load user account management
source('inst/session-mgmt.R')
source('inst/login.R')
source('inst/logout.R')
source('inst/accounts-internal.R')
source('inst/webln.R')

# pages
source("inst/dashboard.R")
source("inst/account-page.R")
source("inst/reports.R")
source("inst/node-stats.R")
source('inst/byoc.R')
source('inst/chan-sim.R')
source('inst/capfee-sim.R')
source('inst/rebal-sim.R')
source("inst/faq.R")

# load top-level shiny components
source('inst/server.R')
source('inst/ui.R')

onStop(function() {
	cat("\nServer stopped, closing pool\n")
	poolClose(pool)
})
# start the shiny app
shinyApp(ui, server)
#cat(file=stderr(), "debug\n")
